Sys.setlocale("LC_TIME", "English")
library(chron)
d<-read.table("household_power_consumption.txt",sep=";",header = T,na.strings = "?")
d$Time<-times(d$Time)
d$Date<-as.Date(d$Date,'%d/%m/%Y')
d$Global_active_power<-as.numeric(d$Global_active_power)
m<-subset(d,(d$Date=="2007-02-01")|(d$Date=="2007-02-02"))
datetime<-strptime(paste(m$Date, m$Time, sep=" "), "%Y-%m-%d %H:%M:%S")
png("plot3.png",width=480,height=480)
plot(datetime,m$Sub_metering_1,type="l",ylab = "Energy sub metering",xlab="",col="black")
lines(datetime,m$Sub_metering_2,type="l",xlab="",col="red")
lines(datetime,m$Sub_metering_3,type="l",xlab="",col="blue")
legend("topright",lty =1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()