library(chron)
d<-read.table("household_power_consumption.txt",sep=";",header = T,na.strings = "?")
d$Time<-times(d$Time)
d$Date<-as.Date(d$Date,'%d/%m/%Y')
d$Global_active_power<-as.numeric(d$Global_active_power)
m<-subset(d,(d$Date=="2007-02-01")|(d$Date=="2007-02-02"))
png("plot1.png", width=480, height=480) 
hist(m$Global_active_power,xlab = "Global Active Power (kilowatts)",col="red",main="Global Active Power")
dev.off()